### ISSUE TITLE
XD

### ISSUE THREAD

**Issue by gamerzonedub** [baum1810/fixed-token-grabber#19]
💀💀💀
![Screenshot 2023-07-16 014755](https://github.com/baum1810/fixed-token-grabber/assets/109278250/5435ba0b-dfc5-4296-99c8-bd8da35682cd)

**Comment by baum1810** [comment]
yeah it used to be undetected lol u just can use a obfuscator and its undetected again

**Comment by baum1810** [comment]
this one for example https://github.com/baum1810/batchobfuscator
