### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by indexedKid** [baum1810/fixed-token-grabber#2]
Got an issue I don't understand. Happens when running the program at the end.

Screenshot: https://prnt.sc/26cm55d

Also suggestion: get it so it grabs tokens from all the popular browsers, because currently it only takes from the client which you download.

**Comment by baum1810** [comment]
it normaly grabbs the tokens of the browser but it looks like the part where it grabbs the browser tokens doesnt work for you

**Comment by baum1810** [comment]
baum#5842 add me on discord then i can look into that issue

**Comment by indexedKid** [comment]
Just added you :)
